const EQUIPMENTTYPE_DUMBBELL = "dumbbell";
const EQUIPMENTTYPE_BARBELL = "barbell";
const EQUIPMENTTYPE_BODYWEIGHT = "bodyweight";
const EQUIPMENTTYPE_KETTLEBELL = "kettlebell";
const EQUIPMENTTYPE_MEDICINEBALL = "medicine ball";
const EQUIPMENTTYPE_MACHINE = "machine";

const EQUIPMENTTYPES = [
  EQUIPMENTTYPE_DUMBBELL,
  EQUIPMENTTYPE_BARBELL,
  EQUIPMENTTYPE_BODYWEIGHT,
  EQUIPMENTTYPE_KETTLEBELL,
  EQUIPMENTTYPE_MEDICINEBALL,
  EQUIPMENTTYPE_MACHINE,
];
